name: batch-insert

services:
    postgres:
        image: postgres:latest
        container_name: postgres-db
        environment:
            POSTGRES_DB: your_db_name
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
        ports:
            - "5433:5432"