spring:
    application:
        name: BatchInsert

    profiles:
        active: jdbc # specify the active profile (jdbc, jpa, hibernate)

    datasource:
        url: jdbc:postgresql://localhost:5433/your_db_name
        username: your_username
        password: your_password
        driver-class-name: org.postgresql.Driver

    flyway:
        locations: db/migration
        schemas:
            - public
        enabled: true

bath:
    amount: 100 # enter the required number
    csv-file-path: "src/main/resources/csv/file.csv"